# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0f674324bd5beefdd4f0f8df5a266481ada1f051376167e1bfad02f17c6f386ddae0f08b9dbd09c81bc335bca24b244ba14f2de1c2b6b1bff48cb9b7330f7b2

test:
  secret_key_base: 4048394fd36b066cd07b2da352b4a34783e6649533255ac82d36d161dbb159a8edcd9444b2d4cfe56afa866533d31f1a19743654e70a6e04e3884b7705d9a074

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
